In [1]:
from Core.TrainManager import TrainManager
from Config import Config
import numpy as np

In [2]:
means, stds = [], []
for i in range(40):
    config = Config()
    trainManager = TrainManager(config)
    trainManager.current_DS_path = config.prep.tempDir + 'WDF_20.0%_epoch' + str(i) + '/'
    trainManager.init_data_loader()
    mean, std = trainManager.data_loader.dataset.get_normalization()
    print(mean, std)
    means.append(mean)
    stds.append(std)

Adjusting learning rate of group 0 to 2.0000e-05.
_IncompatibleKeys(missing_keys=[], unexpected_keys=['avg_decoder.fc.0.weight', 'avg_decoder.fc.0.bias', 'avg_decoder.fc.1.weight', 'avg_decoder.fc.1.bias', 'avg_decoder.fc.2.weight', 'avg_decoder.fc.2.bias'])
[*] Loading dataset from: /home/kyr/GazeForensicsData/temp/WDF_20.0%_epoch0/
Progress: 7894/7894
[0.42994224 0.3390779  0.30232002] [0.24113849 0.21256849 0.2153381 ]
Adjusting learning rate of group 0 to 2.0000e-05.
_IncompatibleKeys(missing_keys=[], unexpected_keys=['avg_decoder.fc.0.weight', 'avg_decoder.fc.0.bias', 'avg_decoder.fc.1.weight', 'avg_decoder.fc.1.bias', 'avg_decoder.fc.2.weight', 'avg_decoder.fc.2.bias'])
[*] Loading dataset from: /home/kyr/GazeForensicsData/temp/WDF_20.0%_epoch1/
Progress: 7894/7894
[0.42890748 0.33814464 0.30114245] [0.24125259 0.21263145 0.21490451]
Adjusting learning rate of group 0 to 2.0000e-05.
_IncompatibleKeys(missing_keys=[], unexpected_keys=['avg_decoder.fc.0.weight', 'avg_decoder.fc.0.b

In [9]:
print(np.round([np.mean(np.array(means), axis=0), np.mean(np.array(stds), axis=0)], decimals=3))

[[0.428 0.338 0.301]
 [0.241 0.212 0.215]]
